planning_task:
  description: >
    Generate a comprehensive, evidence-based content plan for describing Clear Cell Renal Cell Carcinoma (ccRCC) based on advanced WSI analysis methodologies.
    The plan must include:
    - Systematic structure and hierarchical organization for ccRCC description
    - Key morphological identification characteristics of clear cell morphology to be analyzed and documented
    - Visual and architectural features specific to ccRCC including vascular patterns and growth architecture
    - Cellular characteristics including clear cell cytoplasm, nuclear features, and mitotic activity
    - Immunohistochemical markers relevant to ccRCC diagnosis (CD10, RCC, CK7, Carbonic Anhydrase IX)
    - Differential diagnosis considerations with other renal neoplasms
    - Clinical correlation requirements and prognostic factors (Fuhrman grade, stage)
    - Quality assessment criteria and validation checkpoints for ccRCC
    - JSON output specifications and data structure requirements
    - Integration with ISUP renal pathology guidelines and WHO classification standards
  expected_output: >
    A detailed JSON structure plan containing:
    - Executive summary of ccRCC with epidemiological context and key identifiers
    - Comprehensive data schema with main categories and subcategories for JSON organization
    - Morphological identification characteristics framework with specific ccRCC criteria
    - Visual feature analysis guidelines for clear cell morphology and vascular patterns
    - Cellular architecture evaluation parameters for ccRCC-specific features
    - Immunohistochemical panel specifications and interpretation guidelines for renal markers
    - Differential diagnosis matrix with distinguishing features from other renal tumors
    - Clinical correlation requirements and Fuhrman grading integration
    - JSON validation criteria and data quality protocols
    - Output specifications for structured JSON format with key-value mappings
  agent: wsi_cancer_agent

description_generation_task:
  description: >
    Based on the comprehensive plan from the planning task, generate detailed, medically accurate descriptions for Clear Cell Renal Cell Carcinoma (ccRCC) 
    using advanced WSI analysis expertise. Focus specifically on:
    - Morphological identification characteristics: detailed clear cell morphology, nuclear features, cytoplasmic characteristics, 
      and architectural patterns visible in ccRCC WSI analysis
    - Visual and architectural features: comprehensive description of ccRCC tissue organization, growth patterns, delicate vascular network, 
      and spatial relationships as observed in whole slide images
    - Cellular characteristics: nuclear-to-cytoplasmic ratios, mitotic activity, cellular pleomorphism, and Fuhrman nuclear grading
    - Tissue architecture: solid growth patterns, trabecular arrangements, cystic formations, and infiltrative patterns specific to ccRCC
    - Diagnostic markers: specific morphological features that aid in definitive ccRCC diagnosis
    - Immunohistochemical correlations: relationship between ccRCC morphology and renal cell markers
    - Histopathological grading: integration of morphological features with Fuhrman grading system
    - Vascular and capsular involvement: assessment of invasion patterns and metastatic potential
    - Clinical significance: correlation between ccRCC morphological findings and clinical outcomes
    Utilize the comprehensive knowledge base to ensure medical accuracy, current ISUP guideline compliance, and completeness.
  expected_output: >
    A comprehensive, medically accurate JSON object containing:
    - Detailed morphological identification characteristics with specific ccRCC cellular and architectural features
    - Visual and architectural features with comprehensive WSI-specific descriptions including magnification references
    - Cellular characteristics analysis with quantitative and qualitative assessments for clear cell morphology
    - Tissue architecture description with pattern recognition and classification specific to ccRCC
    - Histopathological markers and diagnostic features with clinical correlation
    - Immunohistochemical profile and renal marker correlations (CD10, RCC, CK7, CAIX)
    - Differential diagnosis considerations with distinguishing morphological features from other renal neoplasms
    - Clinical significance and prognostic implications based on ccRCC morphological findings
    - Fuhrman grading and staging correlations
    - Structured as valid JSON with clear key-value pairs and nested objects for complex data
    - UTF-8 compliant with proper escaping and formatting for direct computational use
  agent: wsi_cancer_agent

description_evaluation_task:
  description: >
    Perform comprehensive medical review and validation of the ccRCC description generated by the description generation task. 
    Conduct systematic evaluation including:
    - Medical accuracy verification: validate all ccRCC morphological descriptions against current renal pathology literature and ISUP guidelines
    - Completeness assessment: ensure all required ccRCC sections from the original plan are thoroughly addressed
    - Terminology consistency: verify proper usage of standardized renal pathology terminology and ccRCC nomenclature
    - Clarity and readability: assess professional language usage and comprehensibility for renal pathologists
    - Guideline compliance: verify adherence to ISUP, WHO, and other relevant international renal pathology standards
    - Diagnostic accuracy: validate that morphological descriptions support accurate ccRCC diagnostic conclusions
    - Content quality assessment: identify weak, unclear, or insufficiently detailed sections regarding ccRCC features
    - Consistency verification: ensure uniform approach and terminology throughout the ccRCC description
    - Gap identification: detect missing critical information or inadequate coverage of important ccRCC features
    - JSON structure validation: verify proper JSON formatting, syntax, and data organization
    Remove or significantly improve any content that does not meet professional medical standards for ccRCC diagnosis.
  expected_output: >
    A rigorously validated, cleaned-up JSON object with:
    - All medical inaccuracies corrected or clearly flagged for expert review
    - Weak, unclear, or insufficiently detailed sections removed or substantially improved
    - Consistent, professional renal pathology terminology throughout
    - Clear, logical JSON organization that follows evidence-based renal pathology reporting standards
    - Comprehensive coverage of all morphological features relevant to ccRCC diagnosis
    - Proper integration of clinical correlations and prognostic factors
    - Detailed validation summary with specific metrics and criteria
    - Compliance verification with international renal pathology guidelines
    - Syntactically valid JSON structure with proper formatting and encoding
    - Quality assurance confirmation for computational and clinical use
  agent: wsi_cancer_agent

finalization_task:
  description: >
    Transform the validated ccRCC description into a final, production-ready JSON object that meets the highest standards of 
    medical data structuring and computational compatibility. Execute comprehensive formatting, organization, and data-export tasks including:
    - Professional JSON structure: implement standardized medical data hierarchy and organization
    - Consistent JSON formatting: apply proper syntax, nested objects, arrays, and data type specifications
    - Medical data standards: ensure compliance with clinical data standards and renal pathology reporting guidelines
    - Data validation: implement comprehensive validation checks for JSON integrity and medical accuracy
    - Schema compliance: ensure adherence to medical informatics standards and digital pathology data schemas
    - UTF-8 encoding: implement proper character encoding and escape sequences for international compatibility
    - Production readiness: ensure JSON meets standards for medical systems, databases, and API integration
    - Accessibility optimization: structure JSON for easy parsing and programmatic access
    - Professional presentation: create a polished, standards-compliant JSON object suitable for clinical and research environments
    - Version control: implement proper data versioning and change tracking metadata
    - Structured data export: construct a valid JSON object where ccRCC morphological features are mapped to standardized data structures
  expected_output: >
    A production-ready JSON object containing:
    - Properly structured nested objects and arrays with clear hierarchical organization
    - Consistent, professional JSON formatting throughout with appropriate data types
    - Complete metadata including cancer type, creation date, version, and data source information
    - Professional medical data structure suitable for clinical and research applications
    - All content validated, finalized, and ready for integration into digital pathology systems
    - Proper formatting of nested structures, arrays, and complex data relationships
    - Clear data organization and logical flow for easy programmatic access
    - Professional data encoding and formatting appropriate for medical informatics
    - UTF-8 compliance with proper character encoding and escape sequences
    - Quality assurance summary confirming final JSON meets all specified standards
    - Version control information and change log summary in metadata
    - Ready for deployment in medical databases, AI applications, or clinical decision support systems
    - Valid JSON syntax (UTF-8, double-quoted keys/values, no comments) optimized for downstream computational applications
  agent: wsi_cancer_agent
