planning_task:
  description: >
    Generate a comprehensive, evidence-based content plan for describing Clear Cell Renal Cell Carcinoma (ccRCC) based on advanced WSI analysis methodologies.
    The plan must include:
    - Systematic structure and hierarchical organization for ccRCC description
    - Key morphological identification characteristics of clear cell morphology to be analyzed and documented
    - Visual and architectural features specific to ccRCC including vascular patterns and growth architecture
    - Cellular characteristics including clear cell cytoplasm, nuclear features, and mitotic activity
    - Immunohistochemical markers relevant to ccRCC diagnosis (CD10, RCC, CK7, Carbonic Anhydrase IX)
    - Differential diagnosis considerations with other renal neoplasms
    - Clinical correlation requirements and prognostic factors (Fuhrman grade, stage)
    - Quality assessment criteria and validation checkpoints for ccRCC
    - JSON output specifications and data structure requirements
    - Integration with ISUP renal pathology guidelines and WHO classification standards
  expected_output: >
    A detailed JSON structure plan containing:
    - Executive summary of ccRCC with epidemiological context and key identifiers
    - Comprehensive data schema with main categories and subcategories for JSON organization
    - Morphological identification characteristics framework with specific ccRCC criteria
    - Visual feature analysis guidelines for clear cell morphology and vascular patterns
    - Cellular architecture evaluation parameters for ccRCC-specific features
    - Immunohistochemical panel specifications and interpretation guidelines for renal markers
    - Differential diagnosis matrix with distinguishing features from other renal tumors
    - Clinical correlation requirements and Fuhrman grading integration
    - JSON validation criteria and data quality protocols
    - Output specifications for structured JSON format with key-value mappings
  agent: wsi_cancer_agent

description_generation_task:
  description: >
    Based on the comprehensive plan from the planning task, generate detailed, medically accurate descriptions for Clear Cell Renal Cell Carcinoma (ccRCC) 
    using advanced WSI analysis expertise. Focus specifically on:
    - Morphological identification characteristics: detailed clear cell morphology, nuclear features, cytoplasmic characteristics, 
      and architectural patterns visible in ccRCC WSI analysis
    - Visual and architectural features: comprehensive description of ccRCC tissue organization, growth patterns, delicate vascular network, 
      and spatial relationships as observed in whole slide images
    - Cellular characteristics: nuclear-to-cytoplasmic ratios, mitotic activity, cellular pleomorphism, and Fuhrman nuclear grading
    - Tissue architecture: solid growth patterns, trabecular arrangements, cystic formations, and infiltrative patterns specific to ccRCC
    - Diagnostic markers: specific morphological features that aid in definitive ccRCC diagnosis
    - Immunohistochemical correlations: relationship between ccRCC morphology and renal cell markers
    - Histopathological grading: integration of morphological features with Fuhrman grading system
    - Vascular and capsular involvement: assessment of invasion patterns and metastatic potential
    - Clinical significance: correlation between ccRCC morphological findings and clinical outcomes
    Utilize the comprehensive knowledge base to ensure medical accuracy, current ISUP guideline compliance, and completeness.
  expected_output: >
    A comprehensive, medically accurate JSON object containing:
    - Detailed morphological identification characteristics with specific ccRCC cellular and architectural features
    - Visual and architectural features with comprehensive WSI-specific descriptions including magnification references
    - Cellular characteristics analysis with quantitative and qualitative assessments for clear cell morphology
    - Tissue architecture description with pattern recognition and classification specific to ccRCC
    - Histopathological markers and diagnostic features with clinical correlation
    - Immunohistochemical profile and renal marker correlations (CD10, RCC, CK7, CAIX)
    - Differential diagnosis considerations with distinguishing morphological features from other renal neoplasms
    - Clinical significance and prognostic implications based on ccRCC morphological findings
    - Fuhrman grading and staging correlations
    - Structured as valid JSON with clear key-value pairs and nested objects for complex data
    - UTF-8 compliant with proper escaping and formatting for direct computational use
  agent: wsi_cancer_agent

description_evaluation_task:
  description: >
    Perform comprehensive medical review and validation of the ccRCC description generated by the description generation task. 
    Conduct systematic evaluation including:
    - Medical accuracy verification: validate all ccRCC morphological descriptions against current renal pathology literature and ISUP guidelines
    - Completeness assessment: ensure all required ccRCC sections from the original plan are thoroughly addressed
    - Terminology consistency: verify proper usage of standardized renal pathology terminology and ccRCC nomenclature
    - Clarity and readability: assess professional language usage and comprehensibility for renal pathologists
    - Guideline compliance: verify adherence to ISUP, WHO, and other relevant international renal pathology standards
    - Diagnostic accuracy: validate that morphological descriptions support accurate ccRCC diagnostic conclusions
    - Content quality assessment: identify weak, unclear, or insufficiently detailed sections regarding ccRCC features
    - Consistency verification: ensure uniform approach and terminology throughout the ccRCC description
    - Gap identification: detect missing critical information or inadequate coverage of important ccRCC features
    - JSON structure validation: verify proper JSON formatting, syntax, and data organization
    Remove or significantly improve any content that does not meet professional medical standards for ccRCC diagnosis.
  expected_output: >
    A rigorously validated, cleaned-up JSON object with:
    - All medical inaccuracies corrected or clearly flagged for expert review
    - Weak, unclear, or insufficiently detailed sections removed or substantially improved
    - Consistent, professional renal pathology terminology throughout
    - Clear, logical JSON organization that follows evidence-based renal pathology reporting standards
    - Comprehensive coverage of all morphological features relevant to ccRCC diagnosis
    - Proper integration of clinical correlations and prognostic factors
    - Detailed validation summary with specific metrics and criteria
    - Compliance verification with international renal pathology guidelines
    - Syntactically valid JSON structure with proper formatting and encoding
    - Quality assurance confirmation for computational and clinical use
  agent: wsi_cancer_agent

finalization_task:
  description: >
    Produce a concise dictionary-of-list JSON summary for the validated Clear Cell Renal Cell Carcinoma (ccRCC) description.
    Requirements:
    - The output must be a single-level JSON object whose only key is the full cancer type string (e.g., "Clear Cell Renal Cell Carcinoma (ccRCC)").
    - The value for that key is an array of 5–15 short, clinically relevant sentences covering gross appearance, microscopic morphology, key molecular/pathogenetic events, and typical clinical presentation.
    - Each sentence must:
        • Start with a capital letter and end with a period.
        • Be self-contained plain text (no markdown formatting, bullet symbols, or nested objects).
        • Avoid redundancy; deduplicate similar statements.
    - Order sentences logically (macroscopic → microscopic → molecular → clinical).
    - Ensure strictly valid JSON: UTF-8, double-quoted keys and strings, no trailing commas or comments.
    - Optimise for downstream LLM/API consumption (compact, readable, minimal nesting).
  expected_output: >
    A valid JSON object in the requested dictionary-of-list format, for example:
    {
      "Clear Cell Renal Cell Carcinoma (ccRCC)": [
        "On gross examination, the tumor characteristically presents as a yellow mass.",
        "Microscopically, the neoplastic cells are defined by their clear cytoplasm.",
        "A key pathogenetic event involves the loss of the VHL tumor suppressor gene.",
        "This genetic loss leads to an increase in the HIF transcription factor.",
        "Increased HIF subsequently promotes the upregulation of VEGF and PDGF.",
        "The pathogenesis is also associated with an increase in insulin-like growth factor 1.",
        "Clinical presentation may include hematuria, flank pain, and a palpable mass."
      ]
    }
  agent: wsi_cancer_agent
